[package]
name = "ocrlocate"
version = "0.1.1"
authors = ["bep"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Index and search a directory of images with OCR (optical character recognition)"
repository = "https://github.com/bepvte/ocrlocate"
keywords = ["ocr", "image", "tesseract"]
categories = ["command-line-utilities", "multimedia::images"]

[features]
bundled = ["tesseract-sys/bundled"]

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["cargo", "string", "env"] }
dirs = "5.0.1"
itertools = "0.12.0"
kdam = { version = "0.5.1", features = ["rayon"] }
leptess = "=0.14.0"
leptonica-sys = "0.4.7"
rayon = "1.8.1"
rusqlite = { version = "0.30.0", features = ["bundled"] }
walkdir = "2.4.0"
tesseract-sys = { path = "./tesseract-sys", version = "=0.5.15" }
glob = "0.3.1"

[patch.crates-io]
tesseract-sys = { path = "./tesseract-sys" }

[workspace]
members = ["tesseract-sys"]
