name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libtesseract-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
